packages:
  - "apps/concords"
  - "apps/footballsocial"
  - "apps/game"
  - "apps/gzip"
  - "apps/teamconcords"
  - "apps/ternent"
  - "apps/platform-game"
  - "packages/encrypt"
  - "packages/game-kit"
  - "packages/identity"
  - "packages/ledger"
  - "packages/proof-of-work"
  - "packages/utils"
