packages:
  - "packages/encrypt"
  - "packages/identity"
  - "packages/utils"
  - "packages/proof-of-work"
  - "packages/ledger"
  - "apps/footballsocial"
  - "apps/teamconcords"
  - "apps/concords"
  - "apps/ternent"
