[package]
name = "blockchain"
version = "0.1.0"
authors = ["Sam Ternent <sam.ternent@gmail.com>"]
description = "A blockchain"
license = "MIT/Apache-2.0"
repository = "https://github.com/samternent/packages/blockchain"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.37"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
age = { version = "0.10.0", features = ["armor", "web-sys"] }
# For key generation
secrecy = "0.8.0"
getrandom = { version = "0.2", features = ["js"] }
sha2 = "0.10"
serde_json = "1.0"

[dependencies.web-sys]
version = "0.3.69"
features = [ "console", "Worker" ]
