apiVersion: apps/v1
kind: Deployment
metadata:
  name: footballsocial-api
  namespace: backend
spec:
  selector:
    matchLabels:
      app: footballsocial-api
  template:
    metadata:
      labels:
        app: footballsocial-api
    spec:
      containers:
        - name: footballsocial-api
          image: samternent/footballsocial-api:latest
          env: 
            - name: SECRET_USERNAME 
              valueFrom: 
                secretKeyRef: 
                  name: newsecret 
                  key: username 
            - name: SECRET_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: newsecret 
                  key: password 
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
