services:
  concords-api:
    image: "samternent/concords-api"
    ports:
      - "8001:4003"
    env_file:
      - '../../.env'

  db:
    image: postgres
    restart: always
    env_file:
      - '../../.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
