apiVersion: v1
kind: Secret
metadata:
  name: ternent-api-ledger
  namespace: backend
type: Opaque
stringData:
  ledger-s3-endpoint: "https://lon1.digitaloceanspaces.com"
  ledger-bucket: "<bucket>"
  ledger-prefix: "pixpax/ledger"
  ledger-access-key-id: "<access-key-id>"
  ledger-secret-access-key: "<secret-access-key>"
  ledger-region: "lon1"
  ledger-flush-max-events: "200"
  ledger-flush-interval-ms: "60000"
  # false = batch by size/interval (default), true = flush each issued pack
  ledger-flush-sync-on-issue: "false"
  # false = do not persist dev/staging issue events to ledger (default)
  ledger-record-dev-issues: "false"
  # Exact schema: JSON array of { keyId, publicKeyPem }
  # keyId must equal sha256(publicKeyPem normalized)
  ledger-trusted-issuer-public-keys-json: "[]"
  issuer-key-id: ""
