apiVersion: v1
kind: Service
metadata:
  name: ternent-api
  namespace: backend
spec:
  ports:
    - name: api
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: ternent-api
