services:
  concords-api:
    image: "samternent/ternent-api"
    ports:
      - "6661:4001"
    env_file:
      - '../../.env'

  db:
    image: postgres
    restart: always
    env_file:
      - '../../.env'
    ports:
      - 6662:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 6663:8080
