import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = resolve(scriptDir, "..");
const wasmPath = resolve(packageDir, "pkg", "ternent_rage_wasm_bg.wasm");
const outputPath = resolve(packageDir, "src", "wasm-bytes.ts");

const wasmBase64 = readFileSync(wasmPath).toString("base64");

writeFileSync(
  outputPath,
  [
    "// This file is generated by scripts/embed-wasm.mjs.",
    `export const wasmBase64 = "${wasmBase64}";`,
    "",
  ].join("\n"),
  "utf8"
);
