name: Release seal.ternent.dev
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SEAL_PROJECT_ID }}
  PNPM_CACHE_PATH: ~/.pnpm-store
  PNPM_CACHE_NAME: pnpm-store-cache
  SEAL_IDENTITY: ${{ secrets.SEAL_IDENTITY }}
on:
  push:
    tags:
      - "seal-*.*.*"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get branch name
        id: branch
        run: |
          echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get node version
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build seal app
        run: pnpm build:seal

      - name: Link Vercel project
        run: vercel link --yes --cwd ${{ github.workspace }}/apps/seal --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --cwd ${{ github.workspace }}/apps/seal --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Vercel Environment Information
        run: vercel build --prod --cwd ${{ github.workspace }}/apps/seal --token=${{ secrets.VERCEL_TOKEN }}

      - name: Generate sealed site artifacts
        uses: samternent/seal-action@v1
        with:
          assets-directory: apps/seal/.vercel/output/static

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --cwd ${{ github.workspace }}/apps/seal --token=${{ secrets.VERCEL_TOKEN }}
