name: Release hub.ternent.dev API

on:
  push:
    branches:
      - main
env:
  VITE_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.DEPLOYMENT_KEY }}
          SSH_USER: ${{ secrets.DEPLOYMENT_USER }}
          SSH_HOST: ${{ secrets.DEPLOYMENT_HOST }}

      - name: Deploy hub.ternent.dev
        run: cat deploy-ternent.sh | ssh staging -T
